# Generated by Django 4.0.3 on 2022-03-14 16:34

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='moviebanner',
            name='banner',
            field=models.ImageField(upload_to=base.models.movie_banner_rename),
        ),
        migrations.AlterField(
            model_name='movieposter',
            name='poster',
            field=models.ImageField(upload_to=base.models.movie_poster_rename),
        ),
        migrations.AlterField(
            model_name='tvshowbanner',
            name='banner',
            field=models.ImageField(upload_to=base.models.tvshow_banner_rename),
        ),
        migrations.AlterField(
            model_name='tvshowposter',
            name='poster',
            field=models.ImageField(upload_to=base.models.tvshow_poster_rename),
        ),
    ]
