# Generated by Django 4.0.3 on 2022-03-16 05:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_movie_tagline_alter_moviebanner_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AddField(
            model_name='episode',
            name='storyline',
            field=models.TextField(default='storline'),
        ),
        migrations.AlterField(
            model_name='moviegenre',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.movie'),
        ),
    ]
