# Generated by Django 4.0.3 on 2022-04-25 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plan.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('Null', 'N'), ('Regular', 'R'), ('Standard', 'S'), ('Premium', 'P')], default='N', max_length=45)),
                ('price', models.IntegerField(default=0)),
                ('price_id', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer', models.CharField(blank=True, max_length=65, null=True)),
                ('plan', models.ForeignKey(default=plan.models.setNull, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
